name: Test Suite

on:
  push:
    branches: [master]

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.13.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: node_modules-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: ./

      - name: Run Tests
        run: yarn hardhat test
        working-directory: ./

  slither:
    name: Slither Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.13.1

      - name: Install Slither
        run: |
          pip install slither-analyzer
        working-directory: ./

      - name: Update dependencies
        run: |
          yarn install
        working-directory: ./

      - name: Slither Analyse
        run: |
          slither .
        working-directory: ./
